if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi
#
export GOPATH=~/go
export PGDATA=/home/postgres
export PATH=$HOME/.bin:/usr/local/bin:$HOME/.cargo/bin:$GOPATH/bin:/opt/PostgreSQL/10/bin:$PATH
export EDITOR="nvim"
export PAGER='nvimpager'
export TERM="xterm-256color"
source $HOME/.tmux/tmuxinator.zsh
export GCLOUDIP="35.227.191.184"
alias tmux="tmux -2"
if [ -z "$TMUX" ] && [ ${UID} != 0 ]
then
  tmux attach -t main || (tmux new -s main && tmux kill-session -t 0)
    tmux kill-session -t 0
    exit
  fi
# Prompt Settings
#
export DEFAULT_USER=$USER
POWERLEVEL9K_STATUS_VERBOSE=true
POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_SHORTEN_STRATEGY="truncate middle"
POWERLEVEL9k_SHORTEN_DIR_LENGTH=4
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_RPROMPT_ON_NEWLINE=true
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(custom_linux_icon todo root_indicator ssh context dir dir_writable_joined vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status background_jobs newline newline load ram time)
POWERLEVEL9K_CUSTOM_LINUX_ICON="echo "
POWERLEVEL9K_VCS_GIT_GITHUB_ICON="\uf09b"
POWERLEVEL9K_VCS_GIT_BITBUCKET_ICON="\uf171"
POWERLEVEL9K_VCS_GIT_GITLAB_ICON="\uf296"
POWERLEVEL9K_VCS_GIT_ICON="\uf1d2"
POWERLEVEL9K_EXECUTION_TIME_ICON="\uf085"
POWERLEVEL9K_FOLDER_ICON="\uf07c"
POWERLEVEL9K_GO_ICON="\ue724"
POWERLEVEL9K_HOME_ICON="\uf015"
POWERLEVEL9K_LINUX_ICON=""
POWERLEVEL9K_LOAD_ICON="CPU \uf0e4"
POWERLEVEL9K_NODE_ICON="\ue718"
POWERLEVEL9K_PYTHON_ICON="\ue73c"
POWERLEVEL9K_RAM_ICON="\uf2db"
POWERLEVEL9K_PUBLIC_IP_ICON="\ue23f"
POWERLEVEL9K_NETWORK_ICON="\uf0c1"
POWERLEVEL9K_RUBY_ICON="\ue739"
POWERLEVEL9K_RUST_ICON="\ue7a8"
POWERLEVEL9K_SERVER_ICON="\uf233"
POWERLEVEL9K_SSH_ICON="\uf101"
POWERLEVEL9K_SWIFT_ICON="\ue755"
POWERLEVEL9K_VCS_BOOKMARK_ICON="\uf02e"
POWERLEVEL9K_VCS_COMMIT_ICON="\ue729"
POWERLEVEL9K_VCS_TAG_ICON="\uf02b"
POWERLEVEL9K_INCOMING_CHANGES_ICON="\uf019"
POWERLEVEL9K_OUTGOING_CHANGES_ICON="\uf093"
POWERLEVEL9K_BATTERY_STAGES=($"\uf244" "\uf243" "\uf242" "\uf241" "\uf240")
POWERLEVEL9K_WINDOWS_ICON="\ue62a"
POWERLEVEL9K_OS_ICON_BACKGROUND="black"
POWERLEVEL9K_OS_ICON_FOREGROUND="white"
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND="red"
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_BACKGROUND="black"
POWERLEVEL9K_DIR_HOME_BACKGROUND="black"
POWERLEVEL9K_DIR_HOME_FOREGROUND="blue"
POWERLEVEL9K_CUSTOM_LINUX_ICON_BACKGROUND="black"
POWERLEVEL9K_CUSTOM_LINUX_ICON_FOREGROUND="white"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="black"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="blue"
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="black"
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="blue"
POWERLEVEL9K_VCS_CLEAN_BACKGROUND="black"
POWERLEVEL9K_VCS_CLEAN_FOREGROUND="green"
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND="black"
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND="black"
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND="yellow"
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND="yellow"
alias vi="nvim"
alias vim="nvim"
alias eoit="sudo eopkg it"
alias eoup="sudo eopkg up"
alias eorm="sudo eopkg rm"
alias eosr="eopkg sr"
alias zsource="source ~/.zshrc"
#
#Custom Scripts
#

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/thor/Downloads/cloud/google-cloud-sdk/path.zsh.inc' ]; then source '/home/thor/Downloads/cloud/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/thor/Downloads/cloud/google-cloud-sdk/completion.zsh.inc' ]; then source '/home/thor/Downloads/cloud/google-cloud-sdk/completion.zsh.inc'; fi
